/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: valmirt (https://sketchfab.com/valmirt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/solar-system-d3f058bbe20e4f70b2b52277ff8e109a
title: Solar System
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sol1_lambert2_0: THREE.Mesh
    Sol1_lambert3_0: THREE.Mesh
    Sol1_lambert4_0: THREE.Mesh
    Sol1_lambert5_0: THREE.Mesh
    Sol1_lambert6_0: THREE.Mesh
    Sol1_lambert7_0: THREE.Mesh
    Sol1_lambert10_0: THREE.Mesh
    Sol1_lambert11_0: THREE.Mesh
    Sol1_lambert12_0: THREE.Mesh
    Sol1_lambert13_0: THREE.Mesh
    Sol1_lambert9_0: THREE.Mesh
  }
  materials: {
    lambert2: THREE.MeshBasicMaterial
    lambert3: THREE.MeshBasicMaterial
    lambert4: THREE.MeshBasicMaterial
    lambert5: THREE.MeshBasicMaterial
    lambert6: THREE.MeshBasicMaterial
    lambert7: THREE.MeshBasicMaterial
    lambert10: THREE.MeshBasicMaterial
    lambert11: THREE.MeshBasicMaterial
    lambert12: THREE.MeshBasicMaterial
    lambert13: THREE.MeshBasicMaterial
    lambert9: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Sol1_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.Sol1_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.Sol1_lambert4_0.geometry} material={materials.lambert4} />
          <mesh geometry={nodes.Sol1_lambert5_0.geometry} material={materials.lambert5} />
          <mesh geometry={nodes.Sol1_lambert6_0.geometry} material={materials.lambert6} />
          <mesh geometry={nodes.Sol1_lambert7_0.geometry} material={materials.lambert7} />
          <mesh geometry={nodes.Sol1_lambert10_0.geometry} material={materials.lambert10} />
          <mesh geometry={nodes.Sol1_lambert11_0.geometry} material={materials.lambert11} />
          <mesh geometry={nodes.Sol1_lambert12_0.geometry} material={materials.lambert12} />
          <mesh geometry={nodes.Sol1_lambert13_0.geometry} material={materials.lambert13} />
          <mesh geometry={nodes.Sol1_lambert9_0.geometry} material={materials.lambert9} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
