/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: WitmerLab at Ohio University (https://sketchfab.com/witmerlab)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/visible-interactive-human-exploding-skull-252887e2e755427c90d9e3d0c6d3025f
title: Visible Interactive Human - Exploding skull
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Left_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    OccipitalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Right_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Right_maxSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    right_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    right_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Right_ParietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Right_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Right_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    TeethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0: THREE.Mesh
    VomerSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1: THREE.Mesh
    FrontalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Inferior_conchaeSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    left_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1: THREE.Mesh
    Left_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Left_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Left_parietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    left_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    SphenoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
    Lower_teethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0: THREE.Mesh
    MandibleSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0: THREE.Mesh
  }
  materials: {
    pasted__lambert5: THREE.MeshStandardMaterial
    pasted__phong3: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/scene.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.25, 5.88, 0.96]} rotation={[-2.35, 0, -0.08]}>
            <group position={[0.03, -0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .Left_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Left_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0, 0.02, 0.01]}>
              <mesh
                geometry={
                  nodes
                    .OccipitalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .OccipitalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.01, -0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .Right_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Right_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.02, 0, 0]}>
              <mesh
                geometry={
                  nodes
                    .Right_maxSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Right_maxSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.01, -0.02, -0.02]}>
              <mesh
                geometry={
                  nodes
                    .right_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .right_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.02, 0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .right_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .right_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.02, -0.01, 0.01]}>
              <mesh
                geometry={
                  nodes
                    .Right_ParietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Right_ParietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.02, 0, 0]}>
              <mesh
                geometry={
                  nodes
                    .Right_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Right_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[-0.02, -0.02, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .Right_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Right_zygomaticSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0, 0, -0.02]}>
              <mesh
                geometry={
                  nodes
                    .TeethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                    .geometry
                }
                material={
                  nodes
                    .TeethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                    .material
                }
              />
            </group>
            <group position={[0, -0.01, -0.02]}>
              <mesh
                geometry={
                  nodes
                    .VomerSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .VomerSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0, -0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                    .geometry
                }
                material={
                  nodes
                    .EthmoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                    .material
                }
              />
            </group>
            <group position={[0, -0.04, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .FrontalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .FrontalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0, -0.02, -0.02]}>
              <mesh
                geometry={
                  nodes
                    .Inferior_conchaeSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Inferior_conchaeSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0.01, -0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .left_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .left_lacrimalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0.02, 0, 0]}>
              <mesh
                geometry={
                  nodes
                    .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                    .geometry
                }
                material={
                  nodes
                    .Left_maxillaSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0_1
                    .material
                }
              />
            </group>
            <group position={[0.01, -0.02, -0.02]}>
              <mesh
                geometry={
                  nodes
                    .Left_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Left_nasalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0.01, 0.01, -0.01]}>
              <mesh
                geometry={
                  nodes
                    .Left_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Left_palatineSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0.02, -0.01, 0.02]}>
              <mesh
                geometry={
                  nodes
                    .Left_parietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .Left_parietalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <group position={[0.04, 0, 0]}>
              <mesh
                geometry={
                  nodes
                    .left_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .geometry
                }
                material={
                  nodes
                    .left_temporalSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                    .material
                }
              />
            </group>
            <mesh
              geometry={
                nodes
                  .SphenoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                  .geometry
              }
              material={
                nodes
                  .SphenoidSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                  .material
              }
            />
            <group position={[-0.42, -1.66, 0.93]} rotation={[-0.15, 0.02, 0.05]}>
              <group position={[0, 0.01, -0.02]}>
                <mesh
                  geometry={
                    nodes
                      .Lower_teethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                      .geometry
                  }
                  material={
                    nodes
                      .Lower_teethSTL_Output_from_geomagic_Studio__________________________________________________pasted__phong3_0
                      .material
                  }
                />
              </group>
              <group
                name="MandibleSTL_Output_from_geomagic_Studio_________________________________________________"
                position={[0, 0.03, -0.02]}>
                <mesh
                  geometry={
                    nodes
                      .MandibleSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                      .geometry
                  }
                  material={
                    nodes
                      .MandibleSTL_Output_from_geomagic_Studio__________________________________________________pasted__lambert5_0
                      .material
                  }
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
